In [63]:
print('Now extract unique first names and check their gender!')

Now extract unique first names and check their gender!

In [12]:
import pandas as pd

employee_names = pd.read_csv('gender.csv')
employee_names.drop('Index1', axis=1, inplace=True)
employee_names.drop('Index2', axis=1, inplace=True)
employee_names.columns

Index(['full_name', 'first_name', 'gender'], dtype='object')

In [13]:
print(employee_names.info())
employee_names.head(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6183 entries, 0 to 6182
Data columns (total 3 columns):
full_name     6183 non-null object
first_name    6183 non-null object
gender        6183 non-null object
dtypes: object(3)
memory usage: 145.0+ KB
None

                                     full_name first_name     gender
0                             ABDO FARRET NETO       ABDO    unknown
1                   ABMAEL BEZERRA DE OLIVEIRA     ABMAEL    unknown
2                   ABNER CARLOS COSTA DE MELO      ABNER  masculino
3   ABRAHAO SANDERSON NUNES FERNANDES DA SILVA    ABRAHAO    unknown
4                 ACACIA JESSICA MAIA DE MOURA     ACACIA   feminino
5                     ACACIO MEDEIROS NOGUEIRA     ACACIO  masculino
6          ACILENE MARIA BORGES GOMES OLIVEIRA    ACILENE    unknown
7             ACSA NARA DE ARAUJO BRITO BARROS       ACSA   feminino
8                ACYNELLY DAFNE DA SILVA NUNES   ACYNELLY    unknown
9                       ADA CRISTINA SCUDELARI        ADA   feminino
10                ADA ISA CUSTODIO DE MESQUITA        ADA   feminino
11                  ADA LIMA FERREIRA DE SOUSA        ADA   feminino
12                 ADAILDE TEIXEIRA DE ALMEIDA    ADAILDE    unknown
13                    ADAILDO GOMES D ASSUNCAO    ADAILDO    unknown
14                    ADAILSON DA SILVA ISIDRO   ADAILSON    unknown
15                    ADAILTON GARCIA DA SILVA   ADAILTON  masculino
16                  ADALA NAYANA DE SOUSA MATA      ADALA    unknown
17          ADALBERTO ALMEIDA DE ARAUJO JUNIOR  ADALBERTO  masculino
18           ADALBERTO ATSUSHI HAMAGUCHI PORTO  ADALBERTO  masculino
19                 ADALBERTO FABRICIO DA SILVA  ADALBERTO  masculino
20         ADALGIZA CRISTINA GOMES DE OLIVEIRA   ADALGIZA    unknown
21            ADAM RAFAEL GONCALVES CAVALCANTE       ADAM  masculino
22                              ADAMO PERRUCCI      ADAMO  masculino
23                            ADAUTO CHIAMENTI     ADAUTO  masculino
24              ADAUTO LUIZ DE PAIVA FERNANDES     ADAUTO  masculino
25                       ADAUTO SABINO BEZERRA     ADAUTO  masculino
26                  ADDISON RIBEIRO DE ALMEIDA    ADDISON    unknown
27                       ADEILDE LIMA DA SILVA    ADEILDE    unknown
28             ADEILZE MAIA DE MORAIS MEDEIROS    ADEILZE    unknown
29               ADELAIDE MARIA MORAIS AVELINO   ADELAIDE   feminino
..                                         ...        ...        ...
70                     ADRIANA MARQUES ROBERTO    ADRIANA   feminino
71                 ADRIANA MONTEIRO DE ALMEIDA    ADRIANA   feminino
72                          ADRIANA NESI DE SA    ADRIANA   feminino
73               ADRIANA NOBREGA SILVA AZEVEDO    ADRIANA   feminino
74                       ADRIANA OLIVEIRA DIAS    ADRIANA   feminino
75             ADRIANA OLIVEIRA FREIRE DE LIMA    ADRIANA   feminino
76            ADRIANA PAULA DA SILVA ELEUTERIO    ADRIANA   feminino
77                       ADRIANA ROSA CARVALHO    ADRIANA   feminino
78                       ADRIANA SZILAGYI LEAO    ADRIANA   feminino
79                               ADRIANE CENCI    ADRIANE   feminino
80                ADRIANE DENISE FONSECA LOPES    ADRIANE   feminino
81                  ADRIANE TRAMONTIN SANTIAGO    ADRIANE   feminino
82            ADRIANNE PAULA VIEIRA DE ANDRADE   ADRIANNE   feminino
83                       ADRIANO ARANHA FREIRE    ADRIANO  masculino
84                 ADRIANO BRETANHA LOPES TORT    ADRIANO  masculino
85           ADRIANO CALIMAN FERREIRA DA SILVA    ADRIANO  masculino
86              ADRIANO CARLOS COSTA DE MORAIS    ADRIANO  masculino
87               ADRIANO CHARLES DA SILVA CRUZ    ADRIANO  masculino
88              ADRIANO DE ARAUJO LIMA LIGUORI    ADRIANO  masculino
89                   ADRIANO DE OLIVEIRA SOUSA    ADRIANO  masculino
90                          ADRIANO DOS SANTOS    ADRIANO  masculino
91       ADRIANO HENRIQUE DO NASCIMENTO RANGEL    ADRIANO  masculino
92                        ADRIANO LIMA TROLEIS    ADRIANO  masculino
93                         ADRIANO LOPES GOMES    ADRIANO  masculino
94             ADRIANO LUIS DE CARVALHO ARAUJO    ADRIANO  masculino
95                  ADRIANO MARINHO DOS SANTOS    ADRIANO  masculino
96                     ADRIANO MEDEIROS CAMARA    ADRIANO  masculino
97                      ADRIANO MEDEIROS COSTA    ADRIANO  masculino
98                  ADRIANO MEDEIROS DE ARAUJO    ADRIANO  masculino
99                       ADRIANO ROCHA GERMANO    ADRIANO  masculino

[100 rows x 3 columns]

In [14]:
unique_first_names = employee_names['first_name'].unique()
print(len(unique_first_names))

2263

In [27]:
unknown_unique_first_names = [ ]

for i, row in employee_names.iterrows():
    if row['gender'] == 'unknown':
        first_name = row['first_name']
        if first_name not in unknown_unique_first_names:
            unknown_unique_first_names.append(first_name)

print(len(unknown_unique_first_names))

1133

### Check gender for unknown names

In [5]:
import rpy2.interactive as r
import rpy2.interactive.packages
r.packages.importr("genderBR")
rlib = r.packages.packages
rlib.genderBR

rpy2.robjects.packages.Package as a <module 'genderBR'>

In [28]:
unknown_first_name_df = pd.DataFrame({'first_name': unknown_unique_first_names})
unknown_first_name_df['gender'] = unknown_first_name_df.apply(lambda row: 'unknown', axis=1)
print(unknown_first_name_df.info())
unknown_first_name_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1133 entries, 0 to 1132
Data columns (total 2 columns):
first_name    1133 non-null object
gender        1133 non-null object
dtypes: object(2)
memory usage: 17.8+ KB
None

      first_name   gender
0           ABDO  unknown
1         ABMAEL  unknown
2        ABRAHAO  unknown
3        ACILENE  unknown
4       ACYNELLY  unknown
5        ADAILDE  unknown
6        ADAILDO  unknown
7       ADAILSON  unknown
8          ADALA  unknown
9       ADALGIZA  unknown
10       ADDISON  unknown
11       ADEILDE  unknown
12       ADEILZE  unknown
13      ADELARDO  unknown
14       ADELENA  unknown
15      ADENILDA  unknown
16      ADENYLZA  unknown
17       ADERSON  unknown
18      ADILIANE  unknown
19          ADJA  unknown
20       ADLAREG  unknown
21         ADLEY  unknown
22          ADNA  unknown
23        ADRIAO  unknown
24         ADSON  unknown
25         AIRAN  unknown
26      AISLANIA  unknown
27         AISSA  unknown
28       AKALINE  unknown
29      ALBANYRA  unknown
...          ...      ...
1103       WIARA  unknown
1104    WICLIFFE  unknown
1105      WIEBKE  unknown
1106      WILACI  unknown
1107   WILDERSON  unknown
1108      WILKER  unknown
1109     WILLAME  unknown
1110    WILLIANE  unknown
1111  WILSYNNARA  unknown
1112    WINIFRED  unknown
1113      WOUBER  unknown
1114        YANA  unknown
1115       YANAK  unknown
1116       YANKO  unknown
1117       YASHA  unknown
1118       YCARO  unknown
1119        YOLE  unknown
1120    YULYANNA  unknown
1121        ZAMA  unknown
1122  ZANKENNEDY  unknown
1123    ZENEWTON  unknown
1124         ZEU  unknown
1125      ZILANE  unknown
1126     ZILIANE  unknown
1127      ZILMAR  unknown
1128    ZIRLEIDE  unknown
1129  ZIVANILSON  unknown
1130      ZORANO  unknown
1131     ZULAMAR  unknown
1132     ZULMARA  unknown

[1133 rows x 2 columns]

In [7]:
from time import sleep
from random import randint

In [9]:
from time import time
from IPython.core.display import clear_output

start_time = time()
requests = 0

for _ in range(5):
    # A request would go here
    requests += 1
    sleep(randint(1,3))
    current_time = time()
    elapsed_time = current_time - start_time
    print('Request: {}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
    clear_output(wait = True)

Request: 5; Frequency: 0.712206038057437 requests/s

In [10]:
from warnings import warn

warn("Warning Simulation")

/home/roger/Utils/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Warning Simulation
  This is separate from the ipykernel package so we can avoid doing imports until

In [34]:
# Preparing the monitoring of the loop
start_time = time()
requests = 0

# For all first names whose gender is unknown
for i, row in unknown_first_name_df.iterrows():
    # Loop control
    #if i > 3:
    #    continue

    # Checks the gender
    first_name = row['first_name']
    gender = row['gender']

    try:
        resp_array = rlib.genderBR.get_gender(first_name)
        if (resp_array is not None) and (len(resp_array) > 0):
            gender = resp_array[0]
    except:
        gender = ''

    # Pause the loop
    sleep(randint(5,10))
        
    # Monitor the requests
    requests += 1
    elapsed_time = time() - start_time
    print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
    clear_output(wait = True)

    # Postprocessing
    try:
        gender = gender.lower()
    except:
        gender = ''

    if (gender not in ['male', 'female']):
        gender = 'unknown'
    
    row['gender'] = gender

    #print(first_name + ' / ' + gender)

Request:1133; Frequency: 0.10273864634056598 requests/s

In [36]:
unknown_first_name_df.to_csv('unknown_first_names.csv')
print('Done!')

Done!

In [63]:
for i, row in employee_names.iterrows():
    if row['gender'] != 'unknown':
        continue
    
    first_name = row['first_name']

    rows_ufndf = unknown_first_name_df.loc[unknown_first_name_df['first_name'] == first_name]

    if rows_ufndf.shape[0] < 1:
        continue
    
    #print(rows_ufndf.iloc[0])
    #print(rows_ufndf.iloc[0]['first_name'])
    #print(first_name)
    #print('-')
    
    correct_gender = rows_ufndf.iloc[0]['gender']
    
    if (correct_gender != 'unknown'):
        row['gender'] = correct_gender

print('Done!')

Done!

In [64]:
employee_names.to_csv('employee_names-3.csv')
print('Done!')

Done!